name: "atm10sky-server-secrets"

infisical:
  projectId: "9d2a2e99-dad0-488e-a756-e254548f6115"
  envSlug: "prod"

secrets:
  - secretKey: "CF_API_KEY"

syncAsKubernetesSecret:
  enabled: true
  secretName: "curseforge-api-key"
