minecraftServer:
  difficulty: normal
  whitelist: |
    A_Cubed3
    MasterOfCubesAU
    jl58261
    saiderman
    FawnCobra
    TR_Llama
  ops: |
    MasterOfCubesAU
  eula: true
  icon: https://mocbot.masterofcubesau.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.4a07ee92.png&w=256&q=75
  motd: |
    \u00A74\u00A7lMOCServers | Minecraft\u00A7r\u00A7r
    Playing %MODPACK_NAME% version %MODPACK_VERSION% \u00A7bMC %VERSION%\u00A7r
  serviceType: LoadBalancer
  memory: 8192M
  type: AUTO_CURSEFORGE
  servicePort: 6969
  levelType: skyblockbuilder:skyblock
  autoCurseForge:
    slug: all-the-mods-10-sky
    apiKey:
      existingSecret: curseforge-api-key
      key: CF_API_KEY

extraEnv:
  ALLOW_FLIGHT: "TRUE"

livenessProbe:
  initialDelaySeconds: 180

resources:
  requests:
    memory: 8192Mi
    cpu: 500m

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: new-node
          operator: In
          values:
          - "true"
      weight: 100

persistence:
  storageClassName: "longhorn"
  dataDir:
    Size: 5Gi
    enabled: true

