minecraftServer:
  difficulty: hard
  whitelist: |
    A_Cubed3
    MasterOfCubesAU
    FawnCobra
    jl58261
    saiderman
    Elemental_Se
    sz1357
    Shamrold
    CaptainRisky_364
    bombscare3
  ops: |
    MasterOfCubesAU
    A_Cubed3
  eula: true
  icon: https://mocbot.masterofcubesau.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.4a07ee92.png&w=256&q=75
  motd: |
    \u00A74\u00A7lMOCServers | Minecraft\u00A7r\u00A7r
    Playing %TYPE% \u00A7b%VERSION%\u00A7r
  serviceType: LoadBalancer

resources:
  requests:
    memory: 4096Mi
    cpu: 500m

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: new-node
          operator: In
          values:
          - "true"
      weight: 100

persistence:
  dataDir:
    enabled: true
    existingClaim: mc-server-minecraft-data-longhorn
